export default defineAppConfig({
  title: 'Sink',
  description: 'A Simple / Speedy / Secure Link Shortener with Analytics, 100% run on Cloudflare.',
  image: '/banner.png',
  previewTTL: 300, // 5 minutes
  slugRegex: /^[a-z0-9]+(?:-[a-z0-9]+)*$/i,
  reserveSlug: [
    'api',
    'auth',
    '_assets',
    'assets',
    '_docs',
    'dashboard',
    'docs',
    'image',
    'login',
    'logout',
    'openapi',
    'scalar',
    'swagger',
    '_nuxt',
    '_ipx',
    'favicon',
    'manifest',
    'robots',
    'sitemap',
  ],
})
